
# JCF, Jun-19-2017

# This file contains the names of stubbed-out (empty) functions for
# which experiments may want to create their own versions in separate
# *.py files. Do not edit this file. 

def start_datataking_base(self):
    pass

def stop_datataking_base(self):
    pass

def do_enable_base(self):
    pass

def do_disable_base(self):
    pass

