
# JCF, Dec-4-2016

# Do not edit this file - copy it to a file with a name along the
# lines of "start_datataking_<your experiment's name>.py", delete this
# comment, and put experiment-specific code intended to execute at the
# start of datataking in the start_datataking_base function,
# below. Then make sure that your new file replaces this one in the
# importation of start_datataking_base function near the top of
# daqinterface.py

def start_datataking_base(self):
    pass
